# Generated by Django 4.1.5 on 2023-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainStudioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTrustedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
